#!/bin/bash
# Finetune TexGaussian on verified garment subset from TexVerse.
# Run from CrowdNet root: bash texverse/finetune_texgaussian.sh
#
# Prerequisites:
#   - Renders complete in texverse/renders/
#   - Point clouds in texverse/pointclouds/
#   - Captions + splits generated by prepare_training_data.py

set -e

eval "$(conda shell.bash hook 2>/dev/null)"
conda activate texgaussian
export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH

CUDA_VISIBLE_DEVICES=0 accelerate launch \
    --config_file external/TexGaussian/acc_configs/gpu1.yaml \
    external/TexGaussian/main.py objaverse \
    --workspace texverse/workspace \
    --batch_size 1 \
    --gradient_accumulation_steps 8 \
    --trainlist texverse/garment_train_list.txt \
    --testlist texverse/garment_test_list.txt \
    --text_description texverse/garment_captions.csv \
    --image_dir texverse/renders \
    --pointcloud_dir texverse/pointclouds \
    --resume external/TexGaussian/checkpoints/model.safetensors \
    --lr 1e-4 \
    --num_epochs 100 \
    --use_material True \
    --use_text True \
    --use_checkpoint True \
    --mixed_precision bf16
